export const PlaylistActions = {
  GET_USER_PLAYLISTS_REQUEST: "GET_USER_PLAYLISTS_REQUEST",
  GET_USER_PLAYLISTS_SUCCESS: "GET_USER_PLAYLISTS_SUCCESS",
  GET_USER_PLAYLISTS_FAILURE: "GET_USER_PLAYLISTS_FAILURE",
};
