export const TrackActions = {
  SET_ACTIVE_VIDEO: "SET_ACTIVE_VIDEO",
  GET_TRACKS_REQUEST: "GET_TRACKS_REQUEST",
  GET_TRACKS_SUCCESS: "GET_TRACKS_SUCCESS",
  GET_TRACKS_FAILURE: "GET_TRACKS_FAILURE",
  SHOW_PLAYLISTS: "SHOW_PLAYLISTS",
  HIDE_PLAYLISTS: "HIDE_PLAYLISTS",
  ADD_TRACK_TO_PLAYLIST: "ADD_TRACK_TO_PLAYLIST",
  RESET_ALERT: "RESET_ALERT",
};
